-- Snowflake user creation
-- Step 1: Use an admin role
USE ROLE ACCOUNTADMIN;

-- Step 2: Create the `transform` role and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Step 3: Create a default warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Step 4: Create the `dbt` user and assign to the transform role
CREATE USER IF NOT EXISTS dbt
  PASSWORD='dbtPassword123'
  LOGIN_NAME='dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_NAMESPACE='MOVIELENS.RAW'
  COMMENT='DBT user used for data transformation';
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt;

-- Step 5: Create a database and schema for the MovieLens project
CREATE DATABASE IF NOT EXISTS MOVIELENS;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.RAW;

-- Step 6: Grant permissions to the `transform` role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;

GRANT ALL ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA ANALYTICS.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA ANALYTICS.RAW TO ROLE TRANSFORM;
GRANT ALL ON DATABASE ANALYTICS TO ROLE TRANSFORM;

--Creating stage to connect to AWS S3
CREATE STAGE netflixstage
      URL='s3://netflix-bucket-rt'
  CREDENTIALS=(AWS_KEY_ID='<your-aws-key-id>' AWS_SECRET_KEY='<your-aws-secret-key>');


--Create tables for raw data ingestion
--movies data--
CREATE OR REPLACE TABLE raw_movies (
    movies_id INTEGER,
    title STRING,
    genres STRING );

--Copying data from S3 buckets to raw tables
    COPY INTO MOVIELENS.STAGING.SRC_RATINGSMOVIELENS.RAW.RAW_MOVIES
FROM '@netflixstage/movies.csv'
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

 --ratings data --
 CREATE OR REPLACE TABLE raw_ratings (
    userId INTEGER,
    movieId INTEGER,
    rating FLOAT,
    timestamp BIGINT
 )

 --Copying data into ratings table -- 
     COPY INTO MOVIELENS.RAW.RAW_RATINGS
 FROM '@netflixstage/ratings.csv'
 FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

--Create table for genome scores-- 
CREATE OR REPLACE TABLE raw_genome_scores(   
    movieId INTEGER,
    tagId INTEGER,
    relevance FLOAT
)

--Copying data--
COPY INTO MOVIELENS.RAW.RAW_GENOME_SCORES
FROM '@netflixstage/genome-scores.csv'
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

-- Create raw_tags --
CREATE OR REPLACE TABLE raw_tags (
  userId INTEGER,
  movieId INTEGER,
  tag STRING,
  timestamp BIGINT
);

COPY INTO raw_tags
FROM '@netflixstage/tags.csv'
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
--ON_ERROR = 'CONTINUE';

-- Load raw_genome_tags
CREATE OR REPLACE TABLE raw_genome_tags (
  tagId INTEGER,
  tag STRING
);

COPY INTO raw_genome_tags
FROM '@netflixstage/genome-tags.csv'
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');


-- Load raw_links
CREATE OR REPLACE TABLE raw_links (
  movieId INTEGER,
  imdbId INTEGER,
  tmdbId INTEGER
);

COPY INTO raw_links
FROM '@netflixstage/links.csv'
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

CREATE SCHEMA STAGING

select * from MOVIELENS.STAGING.SRC_RATINGS
drop view MOVIELENS.STAGING.SRC_RATINGS

SELECT * FROM MOVIELENS.RAW.RAW_TAGSMOVIELENS.NFX_DEV.FCT_MOVIE_TAG_GENOME

CREATE SCHEMA DEV

SELECT TOP 1000 * FROM MOVIELENS.STAGING.SRC_MOVIES

DROP SCHEMA STAGINGMOVIELENS.NFX_STAGING

--INCREMENTAL LOAD TEST--

select * from MOVIELENS.NFX_STAGING.SRC_RATINGS order by rating_timestamp desc limit 10

select * from MOVIELENS.NFX_DEV.FCT_MOVIE_RATINGS_INCR order by rating_timestamp desc limit 10

UPDATE MOVIELENS.NFX_STAGING.SRC_RATINGS SET rating_timestamp = '2015-03-31 23:40:02.000 -0700',
rating = 4.6 WHERE user_id = '87586' AND movie_id = '7151'

INSERT INTO MOVIELENS.NFX_STAGING.SRC_RATINGS VALUES ('87777','8909',4.9,'2015-03-31 23:40:02.000 -0700')